version: "3.4"

services:
  rasa:
    restart: always
    image: "jpark2111/wb_yoli:mvp"
    user: root
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    depends_on:
      - duckling
      - app
  app:
    restart: always
    image: "jpark2111/wb_rasa_action:test"
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      TEMPLATE_ID: ${TEMPLATE_ID}
      API_HOST: ${API_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HUGGINGFACEHUB_ADMIN_API_TOKEN: ${HUGGINGFACEHUB_ADMIN_API_TOKEN}
    ports:
      - 5055:5055
  duckling:
    restart: always
    image: "rasa/duckling:latest"
    ports:
      - 8000:8000
    command: ["duckling-example-exe", "-p", "8000", "--no-access-log", "--no-error-log"]
