version: "3.4"

services:
  rasa-server:
    restart: always
    image: "jpark2111/wb_rasa:latest-SG"
    ports:
      - 5006:5005
    volumes:
      - ./:/app
    depends_on:
      - duckling
      - app
  app:
    restart: always
    image: "jpark2111/wealthbuild_rasa_action_server:latest-SG"
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    ports:
      - 5055:5055
  duckling:
    restart: always
    image: "rasa/duckling:latest"
    ports:
      - 8000:8000
    command: ["duckling-example-exe", "-p", "8000", "--no-access-log", "--no-error-log"]
