version: "3.4"

services:
  rasa:
    restart: always
    image: "jpark2111/wb_rasa:latest-SG"
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    depends_on:
      - app
  app:
    restart: always
    image: "jpark2111/wealthbuild_rasa_action_server:latest-SG"
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    ports:
      - 5055:5055
