name: Action Server
on: 
  push:
    branches:
    - 'main'
    paths:
    - 'actions/**'
    - '.github/workflows/custom_action_server.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Action Server image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: action_server
        name: Build an action server with a custom actions
        uses: RasaHQ/action-server-gha@main
        with:
          actions_directory: 'actions'
          requirements_file: 'actions/requirements-actions.txt'
          docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
          docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker_image_name: 'jpark2111/wealthbuild_rasa_action_server'
          docker_image_tag: 'latest'
          dockerfile: 'Dockerfile'
